# -*- coding: utf-8 -*-
"""Performance-Based Salaries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S78wBsl5xvmpgarlxTigKLp8rQI3DM6Y
"""

import pandas as pd
import numpy as np
import kagglehub
import os

path = kagglehub.dataset_download("armaanmartins21/undervalued-football-players")

print("Path to dataset files:", path)

files = os.listdir(path)

print("Files in dataset folder:")
for file in files:
    print(file)

csv_file = [file for file in files if file.endswith(".csv")][0]

df = pd.read_csv(os.path.join(path, csv_file))

print("Dataset loaded successfully!")

print("Original dataset shape:")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("First 5 rows:")
print(df.head())

print("Missing values in each column:")
print(df.isnull().sum())

# Columns that will be used in the model
model_columns = [
    "MP",
    "Starts",
    "Min",
    "90s",
    "Gls",
    "Ast",
    "G+A",
    "xG",
    "xAG",
    "PrgC",
    "PrgP",
    "PrgR",
    "Annual USD"
]

# Remove rows only if they are missing one of the columns we need
original_rows = len(df)

df = df.dropna(subset=model_columns)

rows_removed = original_rows - len(df)

print("Rows before removing missing values:", original_rows)
print("Rows removed:", rows_removed)
print("Rows after removing missing values:", len(df))

print(df[[
    "Player",
    "MP",
    "Gls",
    "Ast",
    "xG",
    "xAG",
    "Annual USD"
]].head(10))

print("Cleaned dataset:")
print(df.head())

print("\nDataset shape:")
print(df.shape)

# Input features
X = df[[        # array of inputs
    "MP",
    "Starts",
    "Min",
    "90s",
    "Gls",
    "Ast",
    "G+A",
    "xG",
    "xAG",
    "PrgC",
    "PrgP",
    "PrgR"
]]

# Output (target)
y = df["Annual USD"]

print(X.head())
print(y.head())

from sklearn.model_selection import train_test_split    # splits dataset into training, validation, and testing cases

# First split: 80% training/validation and 20% testing
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X,
    y,
    test_size=0.2      # 20% of the data for testing
)

# Second split: 80% training and 20% validation
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val,
    y_train_val,
    test_size=0.2      # 20% of the remaining 80% = 16% of total data
)

print("Training data:")
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("\nValidation data:")
print("X_val:", X_val.shape)
print("y_val:", y_val.shape)

print("\nTesting data:")
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Possible hyperparameter values
fit_intercept_values = [True, False]

best_mse = float("inf")
best_params = None

# Try every combination of hyperparameters
for fit_intercept in fit_intercept_values:

    lr_model = LinearRegression(
        fit_intercept=fit_intercept
    )

    # Train using ONLY the training data
    lr_model.fit(X_train, y_train)

    # Make predictions using ONLY the validation data
    val_predictions = lr_model.predict(X_val)

    # Calculate validation MSE
    val_mse = mean_squared_error(y_val, val_predictions)

    print("fit_intercept:", fit_intercept)
    print("Validation MSE:", val_mse)
    print()

    # Keep the best hyperparameters
    if val_mse < best_mse:
        best_mse = val_mse
        best_params = {
            "fit_intercept": fit_intercept
        }

print("Best Linear Regression parameters:")
print(best_params)

print("\nBest Validation MSE:")
print(best_mse)

# Create the Linear Regression model using the best hyperparameters
lr_model = LinearRegression(
    **best_params
)

# Train the model using the training data
lr_model.fit(X_train, y_train)

# Make predictions on the validation set
val_predictions_lr = lr_model.predict(X_val)

print("First 10 validation predictions:")
print(val_predictions_lr[:10])

# Make predictions on the test set
test_predictions_lr = lr_model.predict(X_test)

# Calculate test MSE
mse_test_lr = mean_squared_error(y_test, test_predictions_lr)

print("Linear Regression MSE (Test):", mse_test_lr)

from sklearn.metrics import mean_absolute_error, r2_score

# Calculate Mean Absolute Error (Updated to use test_predictions_lr)
mae = mean_absolute_error(y_test, test_predictions_lr)

# Calculate R² Score (Updated to use test_predictions_lr)
r2 = r2_score(y_test, test_predictions_lr)

print("Mean Absolute Error:", mae)
print("R² Score:", r2)

for i in range(len(X_test)):
    player = df.loc[X_test.index[i], "Player"]

    actual = y_test.iloc[i]
    predicted = test_predictions_lr[i]  # Updated to use test_predictions_lr

    percent_error = abs((actual - predicted) / actual) * 100

    print(f"{player} | Actual: ${actual:,.2f} | Predicted: ${predicted:,.2f} | Error: {percent_error:.2f}%")

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

# Possible hyperparameter values
max_depth_values = [3, 5, 10, 15, 20, None]
min_samples_split_values = [2, 5, 10]
min_samples_leaf_values = [1, 2, 5]

best_mse = float("inf")
best_params = None

# Try every combination of hyperparameters
for max_depth in max_depth_values:
    for min_samples_split in min_samples_split_values:
        for min_samples_leaf in min_samples_leaf_values:

            tree_model = DecisionTreeRegressor(
                max_depth=max_depth,
                min_samples_split=min_samples_split,
                min_samples_leaf=min_samples_leaf,
                random_state=42
            )

            # Train using ONLY the training data
            tree_model.fit(X_train, y_train)

            # Make predictions using ONLY the validation data
            val_predictions_tree = tree_model.predict(X_val)

            # Calculate validation MSE
            val_mse = mean_squared_error(y_val, val_predictions_tree)

            # Keep the best hyperparameters
            if val_mse < best_mse:
                best_mse = val_mse
                best_params = {
                    "max_depth": max_depth,
                    "min_samples_split": min_samples_split,
                    "min_samples_leaf": min_samples_leaf
                }

print("Best Decision Tree parameters:")
print(best_params)

print("\nBest Validation MSE:")
print(best_mse)

# Create the Decision Tree using the best hyperparameters
tree_model = DecisionTreeRegressor(
    **best_params,
    random_state=42
)

# Train the best model using the training data
tree_model.fit(X_train, y_train)

# Make predictions on the validation set
val_predictions_tree = tree_model.predict(X_val)

print("First 10 validation predictions:")
print(val_predictions_tree[:10])

# Make predictions on the test set
test_predictions_tree = tree_model.predict(X_test)

# Calculate test MSE
mse_test_tree = mean_squared_error(y_test, test_predictions_tree)

print("Decision Tree MSE (Test):", mse_test_tree)

for i in range(len(X_test)):
    player = df.loc[X_test.index[i], "Player"]

    actual = y_test.iloc[i]
    predicted = test_predictions_tree[i]

    percent_error = abs((actual - predicted) / actual) * 100

    print(
        f"{player} | "
        f"Actual: ${actual:,.2f} | "
        f"Predicted: ${predicted:,.2f} | "
        f"Error: {percent_error:.2f}%"
    )

from sklearn.metrics import mean_squared_error

# Linear Regression predictions
train_pred_lr = lr_model.predict(X_train)
test_pred_lr = lr_model.predict(X_test)

mse_train_lr = mean_squared_error(y_train, train_pred_lr)
mse_test_lr = mean_squared_error(y_test, test_pred_lr)

print("Linear Regression MSE (Train):", mse_train_lr)
print("Linear Regression MSE (Test):", mse_test_lr)


# Decision Tree predictions
train_pred_tree = tree_model.predict(X_train)
test_pred_tree = tree_model.predict(X_test)

mse_train_tree = mean_squared_error(y_train, train_pred_tree)
mse_test_tree = mean_squared_error(y_test, test_pred_tree)

print("Decision Tree MSE (Train):", mse_train_tree)
print("Decision Tree MSE (Test):", mse_test_tree)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Possible hyperparameter values
n_estimators_values = [50, 100, 200]
max_depth_values = [5, 10, 15, None]
min_samples_split_values = [2, 5, 10]
min_samples_leaf_values = [1, 2, 5]

best_mse = float("inf")
best_params = None

# Try every combination of hyperparameters
for n_estimators in n_estimators_values:
    for max_depth in max_depth_values:
        for min_samples_split in min_samples_split_values:
            for min_samples_leaf in min_samples_leaf_values:

                rf_model = RandomForestRegressor(
                    n_estimators=n_estimators,
                    max_depth=max_depth,
                    min_samples_split=min_samples_split,
                    min_samples_leaf=min_samples_leaf,
                    random_state=42
                )

                # Train using ONLY the training data
                rf_model.fit(X_train, y_train)

                # Make predictions using ONLY the validation data
                val_predictions = rf_model.predict(X_val)

                # Calculate validation MSE
                val_mse = mean_squared_error(y_val, val_predictions)

                # Keep the best hyperparameters
                if val_mse < best_mse:
                    best_mse = val_mse
                    best_params = {
                        "n_estimators": n_estimators,
                        "max_depth": max_depth,
                        "min_samples_split": min_samples_split,
                        "min_samples_leaf": min_samples_leaf
                    }

print("Best Random Forest parameters:")
print(best_params)

print("\nBest Validation MSE:")
print(best_mse)

# Create the Random Forest using the best hyperparameters
rf_model = RandomForestRegressor(
    **best_params,
    random_state=42
)

# Train the model using the training data
rf_model.fit(X_train, y_train)

# Make predictions on the validation set
val_predictions_rf = rf_model.predict(X_val)

print("First 10 validation predictions:")
print(val_predictions_rf[:10])

# Make predictions on the test set
test_predictions_rf = rf_model.predict(X_test)

# Calculate test MSE
mse_test_rf = mean_squared_error(y_test, test_predictions_rf)

print("Random Forest MSE (Test):", mse_test_rf)

for i in range(len(X_test)):
    player = df.loc[X_test.index[i], "Player"]

    actual = y_test.iloc[i]
    predicted = test_predictions_rf[i]

    percent_error = abs((actual - predicted) / actual) * 100

    print(f"{player} | Actual: ${actual:,.2f} | Predicted: ${predicted:,.2f} | Error: {percent_error:.2f}%")

from sklearn.preprocessing import StandardScaler

# Create the scaler
scaler = StandardScaler()

# Fit the scaler ONLY on the training data
X_train_scaled = scaler.fit_transform(X_train)

# Use the same scaler to transform validation and testing data
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

print("Training data scaled:")
print(X_train_scaled[:5])

from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

# Possible hyperparameter values
n_neighbors_values = [3, 5, 10, 15, 20]
weights_values = ["uniform", "distance"]
p_values = [1, 2]

best_mse = float("inf")
best_params = None

# Try every combination of hyperparameters
for n_neighbors in n_neighbors_values:
    for weights in weights_values:
        for p in p_values:

            knn_model = KNeighborsRegressor(
                n_neighbors=n_neighbors,
                weights=weights,
                p=p
            )

            # Train using ONLY the training data
            knn_model.fit(X_train_scaled, y_train)

            # Make predictions using ONLY the validation data
            val_predictions = knn_model.predict(X_val_scaled)

            # Calculate validation MSE
            val_mse = mean_squared_error(y_val, val_predictions)

            # Keep the best hyperparameters
            if val_mse < best_mse:
                best_mse = val_mse
                best_params = {
                    "n_neighbors": n_neighbors,
                    "weights": weights,
                    "p": p
                }

print("Best KNN parameters:")
print(best_params)

print("\nBest Validation MSE:")
print(best_mse)

# Create the KNN model using the best hyperparameters
knn_model = KNeighborsRegressor(
    **best_params
)

# Train the model using the training data
knn_model.fit(X_train_scaled, y_train)

# Make predictions on the validation set
val_predictions_knn = knn_model.predict(X_val_scaled)

print("First 10 validation predictions:")
print(val_predictions_knn[:10])

# Make predictions on the test set
test_predictions_knn = knn_model.predict(X_test_scaled)

# Calculate test MSE
mse_test_knn = mean_squared_error(y_test, test_predictions_knn)

print("KNN MSE (Test):", mse_test_knn)

for i in range(len(X_test)):
    player = df.loc[X_test.index[i], "Player"]

    actual = y_test.iloc[i]
    predicted = test_predictions_knn[i]

    percent_error = abs((actual - predicted) / actual) * 100

    print(f"{player} | Actual: ${actual:,.2f} | Predicted: ${predicted:,.2f} | Error: {percent_error:.2f}%")

from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error

# Possible hyperparameter values
hidden_layer_sizes_values = [
    (50,),
    (100,),
    (50, 50),
    (100, 50)
]

learning_rate_values = [0.001, 0.01]
alpha_values = [0.0001, 0.001, 0.01]

best_mse = float("inf")
best_params = None

# Try every combination of hyperparameters
for hidden_layer_sizes in hidden_layer_sizes_values:
    for learning_rate in learning_rate_values:
        for alpha in alpha_values:

            nn_model = MLPRegressor(
                hidden_layer_sizes=hidden_layer_sizes,
                learning_rate_init=learning_rate,
                alpha=alpha,
                max_iter=1000,
                random_state=42
            )

            # Train using ONLY the training data
            nn_model.fit(X_train_scaled, y_train)

            # Make predictions using ONLY the validation data
            val_predictions = nn_model.predict(X_val_scaled)

            # Calculate validation MSE
            val_mse = mean_squared_error(y_val, val_predictions)

            # Keep the best hyperparameters
            if val_mse < best_mse:
                best_mse = val_mse
                best_params = {
                    "hidden_layer_sizes": hidden_layer_sizes,
                    "learning_rate_init": learning_rate,
                    "alpha": alpha
                }

print("Best Neural Network parameters:")
print(best_params)

print("\nBest Validation MSE:")
print(best_mse)

# Create the Neural Network using the best hyperparameters
nn_model = MLPRegressor(
    **best_params,
    max_iter=1000,
    random_state=42
)

# Train the model using the training data
nn_model.fit(X_train_scaled, y_train)

# Make predictions on the validation set
val_predictions_nn = nn_model.predict(X_val_scaled)

print("First 10 validation predictions:")
print(val_predictions_nn[:10])

# Make predictions on the test set
test_predictions_nn = nn_model.predict(X_test_scaled)

# Calculate test MSE
mse_test_nn = mean_squared_error(y_test, test_predictions_nn)

print("Neural Network MSE (Test):", mse_test_nn)

for i in range(len(X_test)):
    player = df.loc[X_test.index[i], "Player"]

    actual = y_test.iloc[i]
    predicted = test_predictions_nn[i]

    percent_error = abs((actual - predicted) / actual) * 100

    print(f"{player} | Actual: ${actual:,.2f} | Predicted: ${predicted:,.2f} | Error: {percent_error:.2f}%")

from sklearn.metrics import mean_squared_error
import numpy as np

# Calculate validation MSE for each model
mse_val_lr = mean_squared_error(y_val, val_predictions_lr)
mse_val_tree = mean_squared_error(y_val, val_predictions_tree)
mse_val_rf = mean_squared_error(y_val, val_predictions_rf)
mse_val_knn = mean_squared_error(y_val, val_predictions_knn)
mse_val_nn = mean_squared_error(y_val, val_predictions_nn)

print("Linear Regression Validation MSE:", mse_val_lr)
print("Decision Tree Validation MSE:", mse_val_tree)
print("Random Forest Validation MSE:", mse_val_rf)
print("KNN Validation MSE:", mse_val_knn)
print("Neural Network Validation MSE:", mse_val_nn)

# Calculate inverse-MSE scores
inverse_mse = np.array([
    1 / mse_val_lr,
    1 / mse_val_tree,
    1 / mse_val_rf,
    1 / mse_val_knn,
    1 / mse_val_nn
])

# Normalize the weights so they add up to 1
weights = inverse_mse / np.sum(inverse_mse)

weight_lr = weights[0]
weight_tree = weights[1]
weight_rf = weights[2]
weight_knn = weights[3]
weight_nn = weights[4]

print("Linear Regression weight:", weight_lr)
print("Decision Tree weight:", weight_tree)
print("Random Forest weight:", weight_rf)
print("KNN weight:", weight_knn)
print("Neural Network weight:", weight_nn)

print("\nTotal weight:", np.sum(weights))

# Create weighted average of the model predictions
weighted_ensemble_predictions = (
    weight_lr * test_predictions_lr +
    weight_tree * test_predictions_tree +
    weight_rf * test_predictions_rf +
    weight_knn * test_predictions_knn +
    weight_nn * test_predictions_nn
)

print("First 10 weighted ensemble predictions:")
print(weighted_ensemble_predictions[:10])

# Calculate the weighted ensemble MSE
weighted_ensemble_mse = mean_squared_error(
    y_test,
    weighted_ensemble_predictions
)

print("Weighted Ensemble Model MSE:", weighted_ensemble_mse)

# Calculate percent error for each prediction
weighted_ensemble_percent_error = np.abs(
    (y_test - weighted_ensemble_predictions) / y_test
) * 100

print(weighted_ensemble_percent_error.head(10))

# Calculate average percent error
avg_weighted_ensemble_percent_error = np.mean(
    weighted_ensemble_percent_error
)

print(
    f"Weighted Ensemble Average Percent Error: "
    f"{avg_weighted_ensemble_percent_error:.2f}%"
)

# Calculate percent error for each prediction
weighted_ensemble_percent_error = np.abs(
    (y_test - weighted_ensemble_predictions) / y_test
) * 100

print(weighted_ensemble_percent_error.head(10))

# Calculate average percent error
avg_weighted_ensemble_percent_error = np.mean(
    weighted_ensemble_percent_error
)

print(
    f"Weighted Ensemble Average Percent Error: "
    f"{avg_weighted_ensemble_percent_error:.2f}%"
)

# Use the validation predictions from each existing model as inputs
meta_X_train = np.column_stack([
    val_predictions_lr,
    val_predictions_tree,
    val_predictions_rf,
    val_predictions_knn,
    val_predictions_nn
])

# The actual validation salaries are the target
meta_y_train = y_val

print("Meta-model input shape:")
print(meta_X_train.shape)

print("\nFirst validation example:")
print(meta_X_train[0])

print("\nActual salary:")
print(meta_y_train.iloc[0])

from sklearn.linear_model import LinearRegression

# Create the meta-model
meta_model = LinearRegression()

# Train the meta-model using the validation predictions
meta_model.fit(meta_X_train, meta_y_train)

print("Meta-model trained successfully!")

# Use the test predictions from each existing model as inputs
meta_X_test = np.column_stack([
    test_predictions_lr,
    test_predictions_tree,
    test_predictions_rf,
    test_predictions_knn,
    test_predictions_nn
])

print("Meta-model test input shape:")
print(meta_X_test.shape)

print("\nFirst test example:")
print(meta_X_test[0])

# Make the final salary prediction
meta_predictions = meta_model.predict(meta_X_test)

print("First 10 final predictions:")
print(meta_predictions[:10])

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Calculate evaluation metrics
meta_mse = mean_squared_error(y_test, meta_predictions)
meta_mae = mean_absolute_error(y_test, meta_predictions)
meta_r2 = r2_score(y_test, meta_predictions)

print("Meta-Model MSE:", meta_mse)
print("Meta-Model MAE:", meta_mae)
print("Meta-Model R² Score:", meta_r2)

# Calculate percent error
meta_percent_error = np.abs(
    (y_test - meta_predictions) / y_test
) * 100

print(meta_percent_error.head(10))

# Calculate average percent error
avg_meta_percent_error = np.mean(meta_percent_error)

print(
    f"Meta-Model Average Percent Error: "
    f"{avg_meta_percent_error:.2f}%"
)

for i in range(len(X_test)):
    player = df.loc[X_test.index[i], "Player"]

    actual = y_test.iloc[i]
    predicted = meta_predictions[i]

    percent_error = abs((actual - predicted) / actual) * 100

    print(
        f"{player} | "
        f"Actual: ${actual:,.2f} | "
        f"Predicted: ${predicted:,.2f} | "
        f"Error: {percent_error:.2f}%"
    )

model_names = [
    "Linear Regression",
    "Decision Tree",
    "Random Forest",
    "KNN",
    "Neural Network"
]

print("Meta-model coefficients:")

for name, coefficient in zip(model_names, meta_model.coef_):
    print(f"{name}: {coefficient:.4f}")

print("\nMeta-model intercept:")
print(meta_model.intercept_)

# Use the validation predictions from each existing model as inputs
meta_X_train = np.column_stack([
    val_predictions_lr,
    val_predictions_tree,
    val_predictions_rf,
    val_predictions_knn,
    val_predictions_nn
])

# The actual validation salaries are the target
meta_y_train = y_val

print("Meta-model training input shape:")
print(meta_X_train.shape)

print("\nFirst validation example:")
print(meta_X_train[0])

print("\nActual salary:")
print(meta_y_train.iloc[0])

from sklearn.preprocessing import StandardScaler

# Create the scaler
meta_scaler = StandardScaler()

# Fit the scaler using the validation predictions
meta_X_train_scaled = meta_scaler.fit_transform(meta_X_train)

print("Scaled meta-model inputs:")
print(meta_X_train_scaled[:5])

from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error

# Possible hyperparameter values
hidden_layer_sizes_values = [
    (10,),
    (20,),
    (10, 10),
    (20, 10)
]

learning_rate_values = [0.001, 0.01]
alpha_values = [0.0001, 0.001, 0.01]

best_mse = float("inf")
best_params = None

# Try every combination of hyperparameters
for hidden_layer_sizes in hidden_layer_sizes_values:
    for learning_rate in learning_rate_values:
        for alpha in alpha_values:

            meta_nn_model = MLPRegressor(
                hidden_layer_sizes=hidden_layer_sizes,
                learning_rate_init=learning_rate,
                alpha=alpha,
                max_iter=3000,
                early_stopping=True,
                validation_fraction=0.1,
                n_iter_no_change=20,
                random_state=42
            )

            # Train using the validation predictions
            meta_nn_model.fit(meta_X_train_scaled, meta_y_train)

            # Make predictions
            meta_val_predictions = meta_nn_model.predict(meta_X_train_scaled)

            # Calculate MSE
            meta_val_mse = mean_squared_error(
                meta_y_train,
                meta_val_predictions
            )

            print(
                "Hidden layers:", hidden_layer_sizes,
                "| Learning rate:", learning_rate,
                "| Alpha:", alpha,
                "| MSE:", meta_val_mse
            )

            # Keep the best hyperparameters
            if meta_val_mse < best_mse:
                best_mse = meta_val_mse
                best_params = {
                    "hidden_layer_sizes": hidden_layer_sizes,
                    "learning_rate_init": learning_rate,
                    "alpha": alpha
                }

print("\nBest Meta Neural Network parameters:")
print(best_params)

print("\nBest Meta Neural Network MSE:")
print(best_mse)

# Create the Neural Network using the best hyperparameters
meta_nn_model = MLPRegressor(
    **best_params,
    max_iter=3000,
    early_stopping=True,
    validation_fraction=0.1,
    n_iter_no_change=20,
    random_state=42
)

# Train the best meta-model
meta_nn_model.fit(meta_X_train_scaled, meta_y_train)

print("Meta Neural Network trained successfully!")

# Use the test predictions from each existing model
meta_X_test = np.column_stack([
    test_predictions_lr,
    test_predictions_tree,
    test_predictions_rf,
    test_predictions_knn,
    test_predictions_nn
])

# Scale using the SAME scaler used for training
meta_X_test_scaled = meta_scaler.transform(meta_X_test)

print("Meta-model test input shape:")
print(meta_X_test.shape)

print("\nFirst test example:")
print(meta_X_test[0])

# Make final salary predictions
meta_predictions = meta_nn_model.predict(meta_X_test_scaled)

print("First 10 final predictions:")
print(meta_predictions[:10])

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Calculate evaluation metrics
meta_mse = mean_squared_error(y_test, meta_predictions)
meta_mae = mean_absolute_error(y_test, meta_predictions)
meta_r2 = r2_score(y_test, meta_predictions)

print("Meta Neural Network MSE:", meta_mse)
print("Meta Neural Network MAE:", meta_mae)
print("Meta Neural Network R² Score:", meta_r2)

# Calculate percent error
meta_percent_error = np.abs(
    (y_test - meta_predictions) / y_test
) * 100

print(meta_percent_error.head(10))

# Calculate average percent error
avg_meta_percent_error = np.mean(meta_percent_error)

print(
    f"Meta Neural Network Average Percent Error: "
    f"{avg_meta_percent_error:.2f}%"
)

for i in range(len(X_test)):
    player = df.loc[X_test.index[i], "Player"]

    actual = y_test.iloc[i]
    predicted = meta_predictions[i]

    percent_error = abs((actual - predicted) / actual) * 100

    print(
        f"{player} | "
        f"Actual: ${actual:,.2f} | "
        f"Predicted: ${predicted:,.2f} | "
        f"Error: {percent_error:.2f}%"
    )

print("Model Performance Comparison")
print("-----------------------------------")

print("Linear Regression MSE:", mse_test_lr)
print("Decision Tree MSE:", mse_test_tree)
print("Random Forest MSE:", mse_test_rf)
print("KNN MSE:", mse_test_knn)
print("Neural Network MSE:", mse_test_nn)
print("Weighted Ensemble MSE:", weighted_ensemble_mse)
print("Meta Neural Network MSE:", meta_mse)

model_mse = {
    "Linear Regression": mse_test_lr,
    "Decision Tree": mse_test_tree,
    "Random Forest": mse_test_rf,
    "KNN": mse_test_knn,
    "Neural Network": mse_test_nn,
    "Weighted Ensemble": weighted_ensemble_mse,
    "Meta Neural Network": meta_mse
}

best_model = min(model_mse, key=model_mse.get)
best_mse = model_mse[best_model]

print("Best Model:", best_model)
print("Best Test MSE:", best_mse)

# Calculate average percent error for each model

percent_error_lr = np.mean(
    np.abs((y_test - test_predictions_lr) / y_test) * 100
)

percent_error_tree = np.mean(
    np.abs((y_test - test_predictions_tree) / y_test) * 100
)

percent_error_rf = np.mean(
    np.abs((y_test - test_predictions_rf) / y_test) * 100
)

percent_error_knn = np.mean(
    np.abs((y_test - test_predictions_knn) / y_test) * 100
)

percent_error_nn = np.mean(
    np.abs((y_test - test_predictions_nn) / y_test) * 100
)

percent_error_ensemble = np.mean(
    np.abs((y_test - weighted_ensemble_predictions) / y_test) * 100
)

percent_error_meta = np.mean(
    np.abs((y_test - meta_predictions) / y_test) * 100
)

print("Linear Regression:", percent_error_lr)
print("Decision Tree:", percent_error_tree)
print("Random Forest:", percent_error_rf)
print("KNN:", percent_error_knn)
print("Neural Network:", percent_error_nn)
print("Weighted Ensemble:", percent_error_ensemble)
print("Meta Neural Network:", percent_error_meta)

model_percent_error = {
    "Linear Regression": percent_error_lr,
    "Decision Tree": percent_error_tree,
    "Random Forest": percent_error_rf,
    "KNN": percent_error_knn,
    "Neural Network": percent_error_nn,
    "Weighted Ensemble": percent_error_ensemble,
    "Meta Neural Network": percent_error_meta
}

best_percent_model = min(
    model_percent_error,
    key=model_percent_error.get
)

print("Best Model by Average Percent Error:", best_percent_model)
print(
    "Average Percent Error:",
    model_percent_error[best_percent_model]
)