# -*- coding: utf-8 -*-
"""Predicting Player Salaries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zIEiG0MnrtBtw4LFGRYQD73aCOa76Rz
"""

import kagglehub
import pandas as pd
import os

# Download the dataset
path = kagglehub.dataset_download("crawford/us-major-league-soccer-salaries")

# Read every CSV file into one DataFrame
dfs = []

for file in os.listdir(path):
    if file.endswith(".csv"):
        season = pd.read_csv(os.path.join(path, file))

        # Store the season as a feature
        season["year"] = file.replace(".csv", "")

        dfs.append(season)

# Combine all seasons
df = pd.concat(dfs, ignore_index=True)

# Count rows before removing missing values
rows_before = len(df)

# Remove rows with missing values
df = df.dropna()

# Count rows after removing missing values
rows_after = len(df)
rows_dropped = rows_before - rows_after

# Keep only the columns needed for your model
df = df[[
    "club",
    "first_name",
    "last_name",
    "position",
    "guaranteed_compensation",
    "base_salary",
    "year"
]]

print(df.head())
print(df.shape)

print(f"Rows before dropna(): {rows_before}")
print(f"Rows after dropna(): {rows_after}")
print(f"Rows dropped: {rows_dropped}")



# Input features
X = df[[        #array of inputs
    "club",
    "first_name",
    "last_name",
    "position",
    "guaranteed_compensation"
]]

# Output (target)
y = df["base_salary"]

print(X.head())
print(y.head())

from sklearn.model_selection import train_test_split    #splits dataset into training and testing cases

# Split the data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2      # 20% of the data for testing
)

print("First training example (X_train):")
print(X_train.iloc[0])

print("\nCorresponding target value (y_train):")
print(y_train.iloc[0])

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

categorical_features = [
    "club",
    "first_name",
    "last_name",
    "position"
]

numeric_features = [
    "guaranteed_compensation"
]

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
        ("num", "passthrough", numeric_features)
    ]
)

model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

model.fit(X_train, y_train)

predictions = model.predict(X_test)

print(predictions[:10])

from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("Mean Absolute Error:", mae)
print("R² Score:", r2)

for i in range(len(X_test)):
    first = X_test.iloc[i]["first_name"]
    last = X_test.iloc[i]["last_name"]

    actual = y_test.iloc[i]
    predicted = predictions[i]

    percent_error = abs((actual - predicted) / actual) * 100

    print(f"{first} {last} | Actual: ${actual:,.2f} | Predicted: ${predicted:,.2f} | Error: {percent_error:.2f}%")

#decision tree
from sklearn.tree import DecisionTreeRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, r2_score

tree_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", DecisionTreeRegressor(
        random_state=42,
        max_depth=10   # prevents overfitting (important!)
    ))
])

tree_model.fit(X_train, y_train)
tree_predictions = tree_model.predict(X_test)

mae = mean_absolute_error(y_test, tree_predictions)
r2 = r2_score(y_test, tree_predictions)

print("Decision Tree MAE:", mae)
print("Decision Tree R²:", r2)

for i in range(len(X_test)):
    name = X_test.iloc[i]["first_name"] + " " + X_test.iloc[i]["last_name"]

    actual = y_test.iloc[i]
    predicted = tree_predictions[i]

    print(f"{name} | Actual: ${actual:,.2f} | Predicted: ${predicted:,.2f}")

from sklearn.metrics import mean_squared_error

# predictions already computed from linear model
train_pred_lr = model.predict(X_train)
test_pred_lr = model.predict(X_test)

mse_train_lr = mean_squared_error(y_train, train_pred_lr)
mse_test_lr = mean_squared_error(y_test, test_pred_lr)

print("Linear Regression MSE (Train):", mse_train_lr)
print("Linear Regression MSE (Test):", mse_test_lr)

train_pred_tree = tree_model.predict(X_train)
test_pred_tree = tree_model.predict(X_test)

mse_train_tree = mean_squared_error(y_train, train_pred_tree)
mse_test_tree = mean_squared_error(y_test, test_pred_tree)

print("Decision Tree MSE (Train):", mse_train_tree)
print("Decision Tree MSE (Test):", mse_test_tree)

#Random Forest model
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(
        n_estimators=200,   # number of trees
        random_state=42,
        max_depth=None
    ))
])

rf_model.fit(X_train, y_train)
train_pred_rf = rf_model.predict(X_train)
test_pred_rf = rf_model.predict(X_test)

mse_train_rf = mean_squared_error(y_train, train_pred_rf)
mse_test_rf = mean_squared_error(y_test, test_pred_rf)

print("Random Forest MSE (Train):", mse_train_rf)
print("Random Forest MSE (Test):", mse_test_rf)

rf_percent_error = np.abs((y_test - test_pred_rf) / y_test) * 100

print("Average Percent Error (RF):", np.mean(rf_percent_error))

for i in range(len(X_test)):
    name = X_test.iloc[i]["first_name"] + " " + X_test.iloc[i]["last_name"]

    actual = y_test.iloc[i]
    predicted = test_pred_rf[i]

    error = abs((actual - predicted) / actual) * 100

    print(f"{name} | Actual: ${actual:,.2f} | Predicted: ${predicted:,.2f} | Error: {error:.2f}%")

#KNN model
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error
import numpy as np

categorical_features = ["club", "first_name", "last_name", "position"]
numeric_features = ["guaranteed_compensation"]

preprocessor_knn = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
        ("num", StandardScaler(), numeric_features)
    ]
)

knn_model = Pipeline([
    ("preprocessor", preprocessor_knn),
    ("regressor", KNeighborsRegressor(
        n_neighbors=5
    ))
])

knn_model.fit(X_train, y_train)
train_pred_knn = knn_model.predict(X_train)
test_pred_knn = knn_model.predict(X_test)
mse_train_knn = mean_squared_error(y_train, train_pred_knn)
mse_test_knn = mean_squared_error(y_test, test_pred_knn)

print("KNN MSE (Train):", mse_train_knn)
print("KNN MSE (Test):", mse_test_knn)

knn_percent_error = np.abs((y_test - test_pred_knn) / y_test) * 100

print("Average Percent Error (KNN):", np.mean(knn_percent_error))

for i in range(len(X_test)):
    name = X_test.iloc[i]["first_name"] + " " + X_test.iloc[i]["last_name"]

    actual = y_test.iloc[i]
    predicted = test_pred_knn[i]

    error = abs((actual - predicted) / actual) * 100

    print(f"{name} | Actual: ${actual:,.2f} | Predicted: ${predicted:,.2f} | Error: {error:.2f}%")

#neural network
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error
import numpy as np

categorical_features = ["club", "first_name", "last_name", "position"]
numeric_features = ["guaranteed_compensation"]

preprocessor_nn = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
        ("num", StandardScaler(), numeric_features)
    ]
)

nn_model = Pipeline([
    ("preprocessor", preprocessor_nn),
    ("regressor", MLPRegressor(
        hidden_layer_sizes=(100, 50),  # 2-layer network
        activation="relu",
        max_iter=500,
        random_state=42
    ))
])

nn_model.fit(X_train, y_train)

train_pred_nn = nn_model.predict(X_train)
test_pred_nn = nn_model.predict(X_test)

mse_train_nn = mean_squared_error(y_train, train_pred_nn)
mse_test_nn = mean_squared_error(y_test, test_pred_nn)

print("Neural Network MSE (Train):", mse_train_nn)
print("Neural Network MSE (Test):", mse_test_nn)

nn_percent_error = np.abs((y_test - test_pred_nn) / y_test) * 100

print("Average Percent Error (NN):", np.mean(nn_percent_error))

for i in range(len(X_test)):
    name = X_test.iloc[i]["first_name"] + " " + X_test.iloc[i]["last_name"]

    actual = y_test.iloc[i]
    predicted = test_pred_nn[i]

    error = abs((actual - predicted) / actual) * 100

    print(f"{name} | Actual: ${actual:,.2f} | Predicted: ${predicted:,.2f} | Error: {error:.2f}%")



#averaging the predictions of all the models
import numpy as np

ensemble_predictions = (
    predictions +
    tree_predictions +
    test_pred_rf +
    test_pred_knn +
    test_pred_nn
) / 5

from sklearn.metrics import mean_squared_error

ensemble_mse = mean_squared_error(y_test, ensemble_predictions)

print("Ensemble Model MSE:", ensemble_mse)

ensemble_train_predictions = (
    train_pred_lr +
    train_pred_tree +
    train_pred_rf +
    train_pred_knn +
    train_pred_nn
) / 5

ensemble_train_mse = mean_squared_error(y_train, ensemble_train_predictions)
ensemble_test_mse = mean_squared_error(y_test, ensemble_predictions)

print("Ensemble Train MSE:", ensemble_train_mse)
print("Ensemble Test MSE:", ensemble_test_mse)

import numpy as np

ensemble_percent_error = np.abs((y_test - ensemble_predictions) / y_test) * 100

print(ensemble_percent_error.head(10))

avg_ensemble_percent_error = np.mean(ensemble_percent_error)

print(f"Ensemble Average Percent Error: {avg_ensemble_percent_error:.2f}%")

#to analyze data: ex. could see the average value in each column of datapoints
print("Numeric column averages:")
print(df.mean(numeric_only=True))

print("\nMost common value in each categorical column:")
print(df[["club", "first_name", "last_name", "position"]].mode().iloc[0])
#non-numerical datapoints tough, you could assign a number to each value but not easy because different words have diff meanings
#important to find the distribution of the output values

import pandas as pd

# Manual input for Kevin De Bruyne
kevin = pd.DataFrame({
    "club": ["Manchester City"],
    "first_name": ["Kevin"],
    "last_name": ["De Bruyne"],
    "position": ["M"],
    "guaranteed_compensation": [20800000]  # Approximate annual compensation (USD)
})

# Individual model predictions
lr_prediction = model.predict(kevin)[0]
dt_prediction = tree_model.predict(kevin)[0]
rf_prediction = rf_model.predict(kevin)[0]
knn_prediction = knn_model.predict(kevin)[0]
nn_prediction = nn_model.predict(kevin)[0]

# Combined (ensemble) prediction
ensemble_prediction = (
    lr_prediction +
    dt_prediction +
    rf_prediction +
    knn_prediction +
    nn_prediction
) / 5

# Display results
print("Salary Predictions for Kevin De Bruyne")
print("-" * 45)
print(f"Linear Regression : ${lr_prediction:,.2f}")
print(f"Decision Tree     : ${dt_prediction:,.2f}")
print(f"Random Forest     : ${rf_prediction:,.2f}")
print(f"KNN               : ${knn_prediction:,.2f}")
print(f"Neural Network    : ${nn_prediction:,.2f}")
print("-" * 45)
print(f"Ensemble Average  : ${ensemble_prediction:,.2f}")

# Remove guaranteed_compensation from the inputs
X_no_gc = X.drop(columns=["guaranteed_compensation"])

# Create new train/test split
from sklearn.model_selection import train_test_split

X_train_no_gc, X_test_no_gc, y_train_no_gc, y_test_no_gc = train_test_split(
    X_no_gc,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_features = [
    "club",
    "first_name",
    "last_name",
    "position"
]

preprocessor_no_gc = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

model_no_gc = Pipeline([
    ("preprocessor", preprocessor_no_gc),
    ("regressor", LinearRegression())
])

model_no_gc.fit(X_train_no_gc, y_train_no_gc)

train_pred_lr_no_gc = model_no_gc.predict(X_train_no_gc)
test_pred_lr_no_gc = model_no_gc.predict(X_test_no_gc)

from sklearn.tree import DecisionTreeRegressor

tree_model_no_gc = Pipeline([
    ("preprocessor", preprocessor_no_gc),
    ("regressor", DecisionTreeRegressor(
        random_state=42,
        max_depth=10
    ))
])

tree_model_no_gc.fit(X_train_no_gc, y_train_no_gc)

train_pred_tree_no_gc = tree_model_no_gc.predict(X_train_no_gc)
test_pred_tree_no_gc = tree_model_no_gc.predict(X_test_no_gc)

from sklearn.ensemble import RandomForestRegressor

rf_model_no_gc = Pipeline([
    ("preprocessor", preprocessor_no_gc),
    ("regressor", RandomForestRegressor(
        n_estimators=200,
        random_state=42
    ))
])

rf_model_no_gc.fit(X_train_no_gc, y_train_no_gc)

train_pred_rf_no_gc = rf_model_no_gc.predict(X_train_no_gc)
test_pred_rf_no_gc = rf_model_no_gc.predict(X_test_no_gc)



from sklearn.neighbors import KNeighborsRegressor

knn_model_no_gc = Pipeline([
    ("preprocessor", preprocessor_no_gc),
    ("regressor", KNeighborsRegressor(n_neighbors=5))
])

knn_model_no_gc.fit(X_train_no_gc, y_train_no_gc)

train_pred_knn_no_gc = knn_model_no_gc.predict(X_train_no_gc)
test_pred_knn_no_gc = knn_model_no_gc.predict(X_test_no_gc)

from sklearn.neural_network import MLPRegressor

nn_model_no_gc = Pipeline([
    ("preprocessor", preprocessor_no_gc),
    ("regressor", MLPRegressor(
        hidden_layer_sizes=(100, 50),
        activation="relu",
        max_iter=500,
        random_state=42
    ))
])

nn_model_no_gc.fit(X_train_no_gc, y_train_no_gc)

train_pred_nn_no_gc = nn_model_no_gc.predict(X_train_no_gc)
test_pred_nn_no_gc = nn_model_no_gc.predict(X_test_no_gc)

from sklearn.metrics import mean_squared_error

comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest",
        "KNN",
        "Neural Network"
    ],
    "Original Test MSE": [
        mse_test_lr,
        mse_test_tree,
        mse_test_rf,
        mse_test_knn,
        mse_test_nn
    ],
    "Without Guaranteed Compensation": [
        mean_squared_error(y_test_no_gc, test_pred_lr_no_gc),
        mean_squared_error(y_test_no_gc, test_pred_tree_no_gc),
        mean_squared_error(y_test_no_gc, test_pred_rf_no_gc),
        mean_squared_error(y_test_no_gc, test_pred_knn_no_gc),
        mean_squared_error(y_test_no_gc, test_pred_nn_no_gc)
    ]
})

print(comparison)

import numpy as np

# ----- Original ensemble -----
ensemble_predictions = (
    predictions +
    tree_predictions +
    test_pred_rf +
    test_pred_knn +
    test_pred_nn
) / 5

ensemble_percent_error = np.abs((y_test - ensemble_predictions) / y_test) * 100
avg_original_percent_error = np.mean(ensemble_percent_error)

# ----- Ensemble without guaranteed compensation -----
ensemble_predictions_no_gc = (
    test_pred_lr_no_gc +
    test_pred_tree_no_gc +
    test_pred_rf_no_gc +
    test_pred_knn_no_gc +
    test_pred_nn_no_gc
) / 5

ensemble_percent_error_no_gc = np.abs(
    (y_test_no_gc - ensemble_predictions_no_gc) / y_test_no_gc
) * 100

avg_no_gc_percent_error = np.mean(ensemble_percent_error_no_gc)

# ----- Print comparison -----
print("Ensemble Average Percent Error")
print("---------------------------------------")
print(f"Original Model:                 {avg_original_percent_error:.2f}%")
print(f"Without Guaranteed Compensation: {avg_no_gc_percent_error:.2f}%")
print(f"Difference:                     {avg_no_gc_percent_error - avg_original_percent_error:.2f}%")